-- Full DDL as provided in the architecture doc
CREATE TABLE USER_MASTER (
    user_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(100) NOT NULL UNIQUE,
    email VARCHAR2(150) NOT NULL UNIQUE,
    password_hash VARCHAR2(255) NOT NULL,
    first_name VARCHAR2(100),
    last_name VARCHAR2(100),
    status CHAR(1) DEFAULT 'A' CHECK(status IN ('A','I')),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE TABLE GROUP_MASTER (
    group_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_code VARCHAR2(50) UNIQUE NOT NULL,
    group_name VARCHAR2(100) NOT NULL,
    description VARCHAR2(255)
);

CREATE TABLE USER_GROUP (
    user_id NUMBER PRIMARY KEY,
    group_id NUMBER NOT NULL,
    CONSTRAINT fk_usergroup_user FOREIGN KEY(user_id) REFERENCES USER_MASTER(user_id),
    CONSTRAINT fk_usergroup_group FOREIGN KEY(group_id) REFERENCES GROUP_MASTER(group_id)
);

CREATE TABLE MODULE_MASTER (
    module_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    module_code VARCHAR2(50) UNIQUE NOT NULL,
    module_name VARCHAR2(100),
    description VARCHAR2(255)
);

CREATE TABLE ACCESS_MASTER (
    access_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    module_id NUMBER NOT NULL,
    access_code VARCHAR2(50) NOT NULL,
    description VARCHAR2(255),
    CONSTRAINT fk_access_module FOREIGN KEY(module_id) REFERENCES MODULE_MASTER(module_id),
    CONSTRAINT uq_access UNIQUE(module_id, access_code)
);

CREATE TABLE GROUP_ACCESS_TEMPLATE (
    group_id NUMBER NOT NULL,
    access_id NUMBER NOT NULL,
    allowed CHAR(1) CHECK(allowed IN ('Y','N')),
    PRIMARY KEY(group_id, access_id),
    FOREIGN KEY(group_id) REFERENCES GROUP_MASTER(group_id),
    FOREIGN KEY(access_id) REFERENCES ACCESS_MASTER(access_id)
);

CREATE TABLE USER_ACCESS (
    user_id NUMBER,
    access_id NUMBER,
    allowed CHAR(1) CHECK(allowed IN ('Y','N')),
    expiry_date DATE,
    PRIMARY KEY(user_id, access_id),
    FOREIGN KEY(user_id) REFERENCES USER_MASTER(user_id),
    FOREIGN KEY(access_id) REFERENCES ACCESS_MASTER(access_id)
);

CREATE TABLE KNOWLEDGE (
    knowledge_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR2(255) NOT NULL,
    description CLOB,
    status VARCHAR2(20) CHECK(status IN ('DRAFT','PENDING','PUBLISHED','REJECTED')),
    created_by NUMBER NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    reviewed_by NUMBER,
    reviewed_at TIMESTAMP,
    rejection_reason CLOB,
    FOREIGN KEY(created_by) REFERENCES USER_MASTER(user_id),
    FOREIGN KEY(reviewed_by) REFERENCES USER_MASTER(user_id)
);

CREATE TABLE KEYWORD (
    keyword_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    keyword_name VARCHAR2(100) UNIQUE NOT NULL
);

CREATE TABLE KNOWLEDGE_KEYWORD (
    knowledge_id NUMBER,
    keyword_id NUMBER,
    PRIMARY KEY(knowledge_id, keyword_id),
    FOREIGN KEY(knowledge_id) REFERENCES KNOWLEDGE(knowledge_id),
    FOREIGN KEY(keyword_id) REFERENCES KEYWORD(keyword_id)
);

CREATE TABLE ATTACHMENT (
    attachment_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    knowledge_id NUMBER NOT NULL,
    file_name VARCHAR2(255),
    content_type VARCHAR2(100),
    file_size NUMBER,
    onedrive_file_id VARCHAR2(255),
    uploaded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY(knowledge_id) REFERENCES KNOWLEDGE(knowledge_id)
);
