-- No FOREIGN KEY constraints anywhere, per policy (internal Oracle DB).
-- Referential integrity for every *_id column below is enforced in the
-- Spring service layer instead (see AccessControlService / UserService /
-- GroupService / ModuleService / AccessService / KnowledgeService).
--
-- All tables prefixed CU_ (Cube).

CREATE TABLE CU_USER_MASTER (
    user_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(100) NOT NULL UNIQUE,
    email VARCHAR2(150) NOT NULL UNIQUE,
    password_hash VARCHAR2(255) NOT NULL,
    first_name VARCHAR2(100),
    last_name VARCHAR2(100),
    status CHAR(1) DEFAULT 'A' CHECK(status IN ('A','I')),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE TABLE CU_GROUP_MASTER (
    group_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_code VARCHAR2(50) UNIQUE NOT NULL,
    group_name VARCHAR2(100) NOT NULL,
    description VARCHAR2(255)
);

CREATE TABLE CU_USER_GROUP (
    user_id NUMBER PRIMARY KEY,
    group_id NUMBER NOT NULL
);

CREATE TABLE CU_MODULE_MASTER (
    module_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    module_code VARCHAR2(50) UNIQUE NOT NULL,
    module_name VARCHAR2(100),
    description VARCHAR2(255)
);

CREATE TABLE CU_ACCESS_MASTER (
    access_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    module_id NUMBER NOT NULL,
    access_code VARCHAR2(50) NOT NULL,
    description VARCHAR2(255),
    CONSTRAINT uq_access UNIQUE(module_id, access_code)
);

CREATE TABLE CU_GROUP_ACCESS_TEMPLATE (
    group_id NUMBER NOT NULL,
    access_id NUMBER NOT NULL,
    allowed CHAR(1) CHECK(allowed IN ('Y','N')),
    PRIMARY KEY(group_id, access_id)
);

CREATE TABLE CU_USER_ACCESS (
    user_id NUMBER,
    access_id NUMBER,
    allowed CHAR(1) CHECK(allowed IN ('Y','N')),
    expiry_date DATE,
    PRIMARY KEY(user_id, access_id)
);

CREATE TABLE CU_KNOWLEDGE (
    knowledge_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR2(255) NOT NULL,
    description CLOB,
    status VARCHAR2(20) CHECK(status IN ('DRAFT','PENDING','PUBLISHED','REJECTED')),
    created_by NUMBER NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    reviewed_by NUMBER,
    reviewed_at TIMESTAMP,
    rejection_reason CLOB,
    search_text CLOB
);

-- Requires CTXAPP granted to this schema: GRANT CTXAPP TO CUBEDB;
CREATE INDEX cu_knowledge_search_idx ON CU_KNOWLEDGE(search_text)
    INDEXTYPE IS CTXSYS.CONTEXT
    PARAMETERS ('SYNC (ON COMMIT)');

CREATE TABLE CU_KEYWORD (
    keyword_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    keyword_name VARCHAR2(100) UNIQUE NOT NULL
);

CREATE TABLE CU_KNOWLEDGE_KEYWORD (
    knowledge_id NUMBER,
    keyword_id NUMBER,
    PRIMARY KEY(knowledge_id, keyword_id)
);

CREATE TABLE CU_ATTACHMENT (
    attachment_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    knowledge_id NUMBER NOT NULL,
    file_name VARCHAR2(255),
    content_type VARCHAR2(100),
    file_size NUMBER,
    onedrive_file_id VARCHAR2(255),
    uploaded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);